### ISSUE TITLE
Start collecting stock data for training.

### ISSUE THREAD

**Issue by guyyatsu** [guyyatsu/BankNode-Broker#3]

**Comment by guyyatsu** [comment]
# To-Do List

- [ ] Allocate Disk
- [ ] Write collection API
- [ ] Create database API
- [ ] Integrate with production
